"""empty message

Revision ID: 057dd2648bf4
Revises: 4b4b67cd9f42
Create Date: 2016-01-02 21:53:47.867037

"""

# revision identifiers, used by Alembic.
revision = '057dd2648bf4'
down_revision = '4b4b67cd9f42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('first_name', sa.String(length=128), nullable=False))
    op.add_column('customer', sa.Column('last_name', sa.String(length=128), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'last_name')
    op.drop_column('customer', 'first_name')
    ### end Alembic commands ###
