"""empty message

Revision ID: 20bee4715011
Revises: 41e443efedbf
Create Date: 2016-03-08 14:02:50.912797

"""

# revision identifiers, used by Alembic.
revision = '20bee4715011'
down_revision = '41e443efedbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'users_profile_photo_key', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'users_profile_photo_key', 'users', ['profile_photo'])
    ### end Alembic commands ###
