"""empty message

Revision ID: 287c15b7ad2c
Revises: a5fc319b46b2
Create Date: 2016-01-11 17:40:32.804767

"""

# revision identifiers, used by Alembic.
revision = '287c15b7ad2c'
down_revision = 'a5fc319b46b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('description', sa.Text(), nullable=True))
    op.drop_constraint(u'user_username_key', 'user', type_='unique')
    op.drop_column('user', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.create_unique_constraint(u'user_username_key', 'user', ['username'])
    op.drop_column('company', 'description')
    ### end Alembic commands ###
