"""empty message

Revision ID: 2e842caf04f1
Revises: bf1b322a8317
Create Date: 2016-02-03 12:11:52.908315

"""

# revision identifiers, used by Alembic.
revision = '2e842caf04f1'
down_revision = 'bf1b322a8317'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from main.models import Location

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('area', sa.String(), nullable=True))
    op.add_column('location', sa.Column('type', sqlalchemy_utils.types.choice.ChoiceType(Location.LOCATION_TYPE), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'type')
    op.drop_column('location', 'area')
    ### end Alembic commands ###
