"""empty message

Revision ID: 4b4b67cd9f42
Revises: None
Create Date: 2016-01-02 20:47:43.722113

"""

# revision identifiers, used by Alembic.
revision = '4b4b67cd9f42'
down_revision = None

from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('password', sqlalchemy_utils.types.password.PasswordType(), nullable=True))
    op.create_unique_constraint(None, 'customer', ['phone'])
    op.add_column('specialist', sa.Column('password', sqlalchemy_utils.types.password.PasswordType(), nullable=True))
    op.create_unique_constraint(None, 'specialist', ['phone'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialist', type_='unique')
    op.drop_column('specialist', 'password')
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_column('customer', 'password')
    ### end Alembic commands ###
