"""empty message

Revision ID: 4b8d5f8aff5a
Revises: a04fec92ed88
Create Date: 2016-01-05 18:46:30.398828

"""

# revision identifiers, used by Alembic.
revision = '4b8d5f8aff5a'
down_revision = 'a04fec92ed88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('logo', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'company', ['logo'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='unique')
    op.drop_column('company', 'logo')
    ### end Alembic commands ###
