"""empty message

Revision ID: 668f39aea372
Revises: 61d83a2589e1
Create Date: 2016-03-06 13:33:20.864087

"""

# revision identifiers, used by Alembic.
revision = '668f39aea372'
down_revision = '61d83a2589e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('room', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'room')
    ### end Alembic commands ###
