"""empty message

Revision ID: 68c7c71f40c9
Revises: 71924d1000be
Create Date: 2016-01-23 15:30:50.628184

"""

# revision identifiers, used by Alembic.
revision = '68c7c71f40c9'
down_revision = '71924d1000be'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('location', sa.Column('longitude', sa.Float(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'longitude')
    op.drop_column('location', 'latitude')
    ### end Alembic commands ###
