"""empty message

Revision ID: 6f4ac9fb04b2
Revises: a76492bda64a
Create Date: 2016-01-14 17:35:49.202414

"""

# revision identifiers, used by Alembic.
revision = '6f4ac9fb04b2'
down_revision = 'a76492bda64a'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from main.models import ACTIVITY_STATUS_TYPES


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column(u'org_org_activity', sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(ACTIVITY_STATUS_TYPES), nullable=True))
    op.add_column(u'service', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'service', 'service_category', ['category_id'], ['id'])
    op.drop_column(u'service', 'domain')
    op.add_column(u'user_org_activity', sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(ACTIVITY_STATUS_TYPES), nullable=True))
    op.add_column(u'user_user_activity', sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(ACTIVITY_STATUS_TYPES), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user_user_activity', 'status')
    op.drop_column(u'user_org_activity', 'status')
    op.add_column(u'service', sa.Column('domain', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_column(u'service', 'category_id')
    op.drop_column(u'org_org_activity', 'status')
    op.drop_table('service_category')
    ### end Alembic commands ###
