"""empty message

Revision ID: 71924d1000be
Revises: 6f4ac9fb04b2
Create Date: 2016-01-17 20:08:10.348532

"""

# revision identifiers, used by Alembic.
revision = '71924d1000be'
down_revision = '6f4ac9fb04b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('state', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'state')
    ### end Alembic commands ###
