"""empty message

Revision ID: 74b71482b7e8
Revises: 4b8d5f8aff5a
Create Date: 2016-01-06 14:20:17.756708

"""

# revision identifiers, used by Alembic.
revision = '74b71482b7e8'
down_revision = '4b8d5f8aff5a'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'company', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column(u'company', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column(u'company', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.add_column(u'company', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column(u'company', sa.Column('website', sqlalchemy_utils.types.url.URLType(), nullable=True))
    op.alter_column(u'company', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'company', ['name'])
    op.create_foreign_key(None, 'company', 'org_category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'company', 'location', ['location_id'], ['id'])
    op.add_column(u'customer', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column(u'customer', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column(u'customer', sa.Column('registration_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'customer', 'location', ['location_id'], ['id'])
    op.add_column(u'location', sa.Column('apartment', sa.Integer(), nullable=True))
    op.drop_column(u'location', 'appartment')
    op.add_column(u'service_activity', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.add_column(u'specialist', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column(u'specialist', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column(u'specialist', sa.Column('registration_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'specialist', 'location', ['location_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialist', type_='foreignkey')
    op.drop_column(u'specialist', 'registration_time')
    op.drop_column(u'specialist', 'location_id')
    op.drop_column(u'specialist', 'confirmed')
    op.drop_column(u'service_activity', 'created_time')
    op.add_column(u'location', sa.Column('appartment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column(u'location', 'apartment')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column(u'customer', 'registration_time')
    op.drop_column(u'customer', 'location_id')
    op.drop_column(u'customer', 'confirmed')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='unique')
    op.alter_column(u'company', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column(u'company', 'website')
    op.drop_column(u'company', 'location_id')
    op.drop_column(u'company', 'created_time')
    op.drop_column(u'company', 'confirmed')
    op.drop_column(u'company', 'category_id')
    op.drop_table('org_category')
    ### end Alembic commands ###
