"""empty message

Revision ID: 818b5bb41b6a
Revises: 3d93a753053e
Create Date: 2016-01-12 22:56:57.409277

"""

# revision identifiers, used by Alembic.
revision = '818b5bb41b6a'
down_revision = '3d93a753053e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('user', 'password',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_column('user', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.alter_column('user', 'password',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_column('company', 'description')
    ### end Alembic commands ###
