"""empty message

Revision ID: 82f9c9780e52
Revises: 239351ce2240
Create Date: 2016-01-06 23:08:27.909566

"""

# revision identifiers, used by Alembic.
revision = '82f9c9780e52'
down_revision = '239351ce2240'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sqlalchemy_utils.types.password.PasswordType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
