"""empty message

Revision ID: a04fec92ed88
Revises: b9c4d6a20a31
Create Date: 2016-01-02 16:18:37.537869

"""

# revision identifiers, used by Alembic.
revision = 'a04fec92ed88'
down_revision = 'b9c4d6a20a31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'specialist', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'specialist', 'company', ['company_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialist', type_='foreignkey')
    op.drop_column(u'specialist', 'company_id')
    op.drop_table('company')
    ### end Alembic commands ###
