"""empty message

Revision ID: a5fc319b46b2
Revises: c05b04d9b40c
Create Date: 2016-01-10 22:15:04.270124

"""

# revision identifiers, used by Alembic.
revision = 'a5fc319b46b2'
down_revision = 'c05b04d9b40c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    ### end Alembic commands ###
