"""empty message

Revision ID: a76492bda64a
Revises: 818b5bb41b6a
Create Date: 2016-01-12 23:22:42.357180

"""

# revision identifiers, used by Alembic.
revision = 'a76492bda64a'
down_revision = '818b5bb41b6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'service', ['title'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='unique')
    ### end Alembic commands ###
