"""empty message

Revision ID: b9c4d6a20a31
Revises: e3608c1587d0
Create Date: 2015-12-21 23:12:48.474048

"""

# revision identifiers, used by Alembic.
revision = 'b9c4d6a20a31'
down_revision = 'e3608c1587d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_activity', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_activity', 'confirmed')
    ### end Alembic commands ###
