"""empty message

Revision ID: bf1b322a8317
Revises: 9acfa2506218
Create Date: 2016-02-01 15:59:32.835061

"""

# revision identifiers, used by Alembic.
revision = 'bf1b322a8317'
down_revision = '9acfa2506218'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from main.models import OrderPost, TIMING_TYPE

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_type', sqlalchemy_utils.types.choice.ChoiceType(OrderPost.PRICE_TYPE), nullable=True),
    sa.Column('currency_type', sqlalchemy_utils.types.currency.CurrencyType(length=3), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('specialist_type', sqlalchemy_utils.types.choice.ChoiceType(OrderPost.SPECIALIST_TYPE), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('timing_type', sqlalchemy_utils.types.choice.ChoiceType(TIMING_TYPE), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_post')
    ### end Alembic commands ###
