"""empty message

Revision ID: c05b04d9b40c
Revises: fa5e6febc82a
Create Date: 2016-01-07 13:28:05.028453

"""

# revision identifiers, used by Alembic.
revision = 'c05b04d9b40c'
down_revision = 'fa5e6febc82a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'description')
    ### end Alembic commands ###
